version: '3.7'

services:

  currency-exchange-service:
    image: vlqhoang/simple-spring-micro-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - currency-network
      - rabbitnetwork
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq

  currency-conversion-service:
    image: vlqhoang/simple-spring-micro-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    networks:
      - currency-network
      - rabbitnetwork
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq

  api-gateway:
    image: vlqhoang/simple-spring-micro-netflix-zuul-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - currency-network
      - rabbitnetwork
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
      spring.zipkin.sender.type: rabbit
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq

  naming-server:
    image: vlqhoang/simple-spring-micro-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    networks:
      - currency-network
      - rabbitnetwork
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always #Restart if there is a problem starting up

  rabbitmq:
    image: rabbitmq:3.8.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitnetwork

networks:
  currency-network:
  rabbitnetwork: